### ISSUE TITLE
Add routes as a taino.constructor argument

### ISSUE THREAD

**Issue by fimion** [Ravavyr/taino-js#2]
currently the routes are hard coded into the constructor function.

[See code here](https://github.com/Ravavyr/taino-js/blob/96905332d632cf6b97eadcaa762dcfd5508c6baa/taino.js#L20-L27)

This should be an argument that gets passed into the constructor, to make it more generic and less hardcoded.

**Comment by Ravavyr** [comment]
just closing, it's been a while.
